name: CI STAGE
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python requirements
        run: |
          sudo apt-get install python3-setuptools
          pip3 install wheel
          pip3 install flake8 pytest
      - name: install requirements.txt
        run: |
          pip3 install -r requirements.txt
      - name: make migrations
        run: |
          python3 manage.py makemigrations
      - name: migrate
        run: |
          python3 manage.py migrate
      - name: Test with pytest
        run: |
          pytest
