name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a sample script
        run: echo Hello, World!
      - name: Run a multiline sample
        run: |
          echo Add other actions
          echo test, deploy your project