name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install requirements.txt
        run: pip3 install -r requirements.txt
      - name: make migrations
        run: python3 manage.py makemigrations
